---
- name: MariaDB | Deploy and Security Instalation
  hosts: ubuntu
  sudo: yes
  tasks:
  
  - name: NETTOOLS | Install ifconfig e etc..
    apt:
      name: net-tools
      state: latest
      update_cache: yes
